name: Image build
on: [pull_request]
jobs:
  ep-build-amd64:
    name: Image build/amd64 LEGACY entrypoint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: ghcr.io/${{ github.repository }}:ep-latest-amd64
          file: images/Dockerfile

  build-amd64:
    name: Image build/amd64 daemonized alternative
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: ghcr.io/${{ github.repository }}:latest-amd64
          file: images/Dockerfile.thick

  build-arm64:
    name: Image build/arm64
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: false
          tags: ghcr.io/${{ github.repository }}:latest-arm64
          file: images/Dockerfile.arm64

  build-arm32:
    name: Image build/arm32
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm32
          push: false
          tags: ghcr.io/${{ github.repository }}:latest-arm32
          file: images/Dockerfile.arm32

  build-ppc64le:
    name: Image build/ppc64le
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/ppc64le
          push: false
          tags: ghcr.io/${{ github.repository }}:latest-ppc64le
          file: images/Dockerfile.ppc64le

  build-s390:
    name: Image build/s390x
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/s390x
          push: false
          tags: ghcr.io/${{ github.repository }}:latest-s390x
          file: images/Dockerfile.s390x
